### ISSUE TITLE
ReCaptcha not working

### ISSUE THREAD

**Issue by zananib** [yunusemregul/koubilgi#2]
It seems like ReCaptcha isn't working using the code you provided, is there a way to use it?
![image](https://user-images.githubusercontent.com/95433458/199645870-f24aa608-ef11-4223-a8cb-ea05ed25bf3a.png)

**Comment by yunusemregul** [comment]
Hello @zananib,

I haven't tested this in a long time but it did work for me at the time. You have to put the sitekey of the site you are trying to use this for, to the below line:
https://github.com/yunusemregul/koubilgi/blob/master/app/src/main/assets/recaptcha.html#L12
 
You can find the sitekey by entering that site and inspecting a captcha using developer tools. You can see how on the below picture:
![image](https://user-images.githubusercontent.com/20087554/200354557-bff65f5d-6b45-4331-a0e3-00ed7e532e18.png)

**Comment by zananib** [comment]
I mean I know, that'd work if I use my own site key. How about using another website's site key to render their ReCaptcha? I found your repository from [this question on Stackoverflow ](https://stackoverflow.com/questions/60922907/logging-into-a-site-that-has-recaptcha/60944452#60944452)  about getting the Recaptcha token from a website that we don't have control over.

Because using their site key will show that error in the screenshot above. Is there a way to avoid that?

**Comment by yunusemregul** [comment]
No the site-key that I used for this application was not mine, it was another website's and it did work for me. One thing that you missed could be that I render the recaptcha on that same site so captcha is at the same domain, I guess you might be trying to render the sitekey on some other domain which is not allowed.

So what I do is I go to that site in my application with webview, empty all the html content and render my own captcha html thus google thinks that captcha request comes from the original site.
